// Generated by CoffeeScript 1.8.0
var Config;

Config = {
  solr: "solr/select?",
  search_params: {
    wt: "json",
    sort: "start desc",
    stats: "true",
    "stats.field": "start"
  },
  packing: 4,
  rows: 30
};
